[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "fade", "--transition-duration", "0.5"]
set = true


[config.reload_apps_list]
kitty = true

[config.custom_colors]
red = { color = "#ff0000", blend = true }
green = { color = "#00ff00", blend = true }
yellow = { color = "#ffff00", blend = true }
blue = { color = "#0000ff", blend = true }
magenta = { color = "#ff00ff", blend = true }
cyan = { color = "#00ffff", blend = true }
white = { color = "#ffffff", blend = true }

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pidof waybar && pkill -SIGUSR2 waybar >/dev/null 2>&1 & '

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload ; ~/.config/hypr/scripts/checkbattery.sh >/dev/null 2>&1 & '

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/theme/colors-matugen.conf'
post_hook = 'killall -SIGUSR1 kitty >/dev/null 2>&1 & '

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty-colors'
output_path = '~/.config/ghostty/themes/matugen'
post_hook = 'systemctl reload --user app-com.mitchellh.ghostty.service >/dev/null 2>&1 & '

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell-colors.qml'
output_path = '~/.config/quickshell/shared/Colors.qml'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/material-colors.rasi'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.fabric]
input_path = '~/.config/matugen/templates/fabric.css'
output_path = '~/.config/fabric/styles/colors.css'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs >/dev/null 2>&1 & '

[templates.papirus-folder]
input_path = '~/.config/matugen/templates/folder-color.txt'
output_path = '~/.cache/averell/papirus-folder.txt'

[templates.swayosd]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swayosd/colors.css'
# post_hook = 'killall swayosd-server; swayosd-server >/dev/null 2>&1 & '

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.json'
output_path = '~/.config/vicinae/themes/matugen.json'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

pre_hook = "~/.local/bin/cache-wallpaper {{image}} >/dev/null 2>&1 & "
post_hook = "~/.local/bin/post-wall"

[templates.fish]
input_path = '~/.config/matugen/templates/colors.fish'
output_path = '~/.config/fish/themes/Matugen.theme'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-bg.lua'
output_path = '~/.config/nvim/lua/config/bg.lua'
