backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
kitty = { template = 'kitty-colors.conf', target = '~/.config/kitty/theme/colors-wallust.conf' }
ghostty = { template = 'ghostty-colors.conf', target = '~/.config/ghostty/themes/wallust' }
hyprland = { template = 'hyprland-colors.conf', target = '~/.config/hypr/colors-wallust.conf' }
waybar = { template = 'colors.css', target = '~/.config/waybar/colors-wallust.css' }
starship = { template = 'starship.toml', target = '~/.config/starship.toml' }
