[colors.primary]
background = '#131313'
foreground = '#f0f0f0'

[colors.cursor]
text = '#f0f0f0'
cursor = '#d0d0d0'

[colors.vi_mode_cursor]
text = '#1a1a1a'
cursor = '#f0f0f0'

[colors.search.matches]
foreground = '#1e1e1e'
background = '#b0b0b0'

[colors.search.focused_match]
foreground = '#1e1e1e'
background = '#f0f0f0'

[colors.footer_bar]
foreground = '#1e1e1e'
background = '#f0f0f0'

[colors.hints.start]
foreground = '#1e1e1e'
background = '#d0d0d0'

[colors.hints.end]
foreground = '#1e1e1e'
background = '#d0d0d0'

[colors.selection]
text = '#1a1a1a'
background = '#f0f0f0'


[colors.normal]
black = '#181818'
red = '#909090'
green = '#f0f0f0'
yellow = '#f0f0f0'
blue = '#f0f0f0'
magenta = '#b0b0b0'
cyan = '#d0d0d0'
white = '#f0f0f0'


[colors.bright]
black = '#404040'
red = '#909090'
green = '#a0a0a0'
yellow = '#b0b0b0'
blue = '#c0c0c0'
magenta = '#d0d0d0'
cyan = '#e0e0e0'
white = '#f0f0f0'


[colors.dim]
black = '#303030'
red = '#909090'
green = '#a0a0a0'
yellow = '#b0b0b0'
blue = '#c0c0c0'
magenta = '#d0d0d0'
cyan = '#e0e0e0'
white = '#f0f0f0'