# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "C"
run = "plugin compress"
desc = "Archive selected files"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[mgr.append_keymap]]
on = ["g", "w"]
run = "cd /run/media/averell/Windows/Users/Averell"
desc = "Go to the Windows directory"

[[mgr.append_keymap]]
on = ["g", "m"]
run = "cd /run/media/averell"
desc = "Go to the media directory"

[[mgr.append_keymap]]
on = ["c", "w"]
run = 'shell -- matugen image "$0"'
desc = "Set the current wallpaper"
