# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.append_keymap]]
on   = ["g", "w"]
run  = "cd /run/media/averell/Windows/Users/Averell"
desc = "Go to the Windows directory"

[[manager.append_keymap]]
on   = ["g", "m"]
run  = "cd /run/media/averell"
desc = "Go to the media directory"
