"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark = "kanagawa"
light = "kanagawa"

# : }}}

# : Status {{{

[status]
# separator_open  = ""
# separator_close = ""
sep_left = { open = "", close = ""}
sep_right = { open = "", close = ""}

# : }}}
