"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

palette = 'colors'

[palettes.colors]
mustard = '#af8700'                                  # example
error = '#E06C75'
success = '#00CF3A'
color1 = '#d4c1d0'
color2 = '#392c38'
color3 = '#cbc5c6'
color4 = '#211f20'
color5 = '#392c38'
color6 = '#151314'
color7 = '#151314'
color8 = '#d4c1d0'
color9 = '#d8bfd4'

# add_newline = true

[time]
disabled = true
format = '[$time]($style) '
time_format = '%H:%M'

[character]
# success_symbol = "[0 ❯](bold green)"
success_symbol = "[0 ➜](bold success)"
error_symbol = "[➜](bold error)"

[directory]
truncation_symbol = '.../'

[git_branch]
truncation_length = 20
symbol = ' '

[gradle]
symbol = ' '

[kotlin]
symbol = ' '

[git_commit]
tag_disabled = false
commit_hash_length = 7
disabled = true

[git_state]
disabled = true

[memory_usage]
format = 'using [$ram_pct RAM]($style) '
disabled = false

[package]
disabled = true

[status]
format = '[$status](color1) '
disabled = false

[aws]
disabled = true
