[window]
decorations = "none"
opacity = 1

[font]
normal = { family = "JetBrainsMono NF" }
size = 15
offset.y = 12

[general]
# import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]
import = ["colors.toml"]
