[window]
decorations = "none"
opacity = 1

[font]
# normal = { family = "JetBrainsMono NF" }
normal = { family = "Maple Mono" }
size = 15
offset.y = 14

[general]
# import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]
import = ["colors.toml"]
