[colors.primary]
background = '#121413'
foreground = '#e3e2e1'

[colors.cursor]
text = '#e3e2e1'
cursor = '#c1c8c7'

[colors.vi_mode_cursor]
text = '#121413'
cursor = '#abcdca'

[colors.search.matches]
foreground = '#414847'
background = '#ecbcab'

[colors.search.focused_match]
foreground = '#414847'
background = '#abcdca'

[colors.footer_bar]
foreground = '#414847'
background = '#e3e2e1'

[colors.hints.start]
foreground = '#414847'
background = '#bcc9c7'

[colors.hints.end]
foreground = '#414847'
background = '#bcc9c7'

[colors.selection]
text = '#121413'
background = '#abcdca'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#abcdca'
yellow = '#446462'
blue = '#abcdca'
magenta = '#ecbcab'
cyan = '#bcc9c7'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
