[colors.primary]
background = '#191112'
foreground = '#f0dee0'
 
[colors.cursor]
text = '#f0dee0'
cursor = '#d6c2c4' 
 
[colors.vi_mode_cursor]
text = '#191112'
cursor = '#ffb2be' 
 
[colors.search.matches]
foreground = '#524345' 
background = '#ebbe90' 
 
[colors.search.focused_match]
foreground = '#524345' 
background = '#ffb2be' 
 
[colors.footer_bar]
foreground = '#524345' 
background = '#f0dee0' 
 
[colors.hints.start]
foreground = '#524345' 
background = '#e4bdc2' 
 
[colors.hints.end]
foreground = '#524345' 
background = '#e4bdc2' 
 
[colors.selection]
text = '#191112'
background = '#ffb2be'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb2be' 
yellow = '#8e4957' 
blue = '#ffb2be' 
magenta = '#ebbe90' 
cyan = '#e4bdc2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
