[colors.primary]
background = '#131315'
foreground = '#e4e2e3'
 
[colors.cursor]
text = '#e4e2e3'
cursor = '#c5c6cd' 
 
[colors.vi_mode_cursor]
text = '#131315'
cursor = '#bbc7df' 
 
[colors.search.matches]
foreground = '#45474c' 
background = '#dcc39b' 
 
[colors.search.focused_match]
foreground = '#45474c' 
background = '#bbc7df' 
 
[colors.footer_bar]
foreground = '#45474c' 
background = '#e4e2e3' 
 
[colors.hints.start]
foreground = '#45474c' 
background = '#c3c6d1' 
 
[colors.hints.end]
foreground = '#45474c' 
background = '#c3c6d1' 
 
[colors.selection]
text = '#131315'
background = '#bbc7df'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bbc7df' 
yellow = '#545f74' 
blue = '#bbc7df' 
magenta = '#dcc39b' 
cyan = '#c3c6d1' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
