[colors.primary]
background = '#121414'
foreground = '#e3e2e2'
 
[colors.cursor]
text = '#e3e2e2'
cursor = '#c2c7c9' 
 
[colors.vi_mode_cursor]
text = '#121414'
cursor = '#b0cbd1' 
 
[colors.search.matches]
foreground = '#424849' 
background = '#e7bea9' 
 
[colors.search.focused_match]
foreground = '#424849' 
background = '#b0cbd1' 
 
[colors.footer_bar]
foreground = '#424849' 
background = '#e3e2e2' 
 
[colors.hints.start]
foreground = '#424849' 
background = '#bec8cb' 
 
[colors.hints.end]
foreground = '#424849' 
background = '#bec8cb' 
 
[colors.selection]
text = '#121414'
background = '#b0cbd1'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b0cbd1' 
yellow = '#496268' 
blue = '#b0cbd1' 
magenta = '#e7bea9' 
cyan = '#bec8cb' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
