[colors.primary]
background = '#121315'
foreground = '#e3e2e5'
 
[colors.cursor]
text = '#e3e2e5'
cursor = '#c2c7ce' 
 
[colors.vi_mode_cursor]
text = '#121315'
cursor = '#a8caeb' 
 
[colors.search.matches]
foreground = '#42474d' 
background = '#edbe87' 
 
[colors.search.focused_match]
foreground = '#42474d' 
background = '#a8caeb' 
 
[colors.footer_bar]
foreground = '#42474d' 
background = '#e3e2e5' 
 
[colors.hints.start]
foreground = '#42474d' 
background = '#bbc8d6' 
 
[colors.hints.end]
foreground = '#42474d' 
background = '#bbc8d6' 
 
[colors.selection]
text = '#121315'
background = '#a8caeb'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a8caeb' 
yellow = '#40617e' 
blue = '#a8caeb' 
magenta = '#edbe87' 
cyan = '#bbc8d6' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
