[colors.primary]
background = '#131314'
foreground = '#e4e2e3'

[colors.cursor]
text = '#e4e2e3'
cursor = '#c4c6cc'

[colors.vi_mode_cursor]
text = '#131314'
cursor = '#c6d3e5'

[colors.search.matches]
foreground = '#44474c'
background = '#eaccae'

[colors.search.focused_match]
foreground = '#44474c'
background = '#c6d3e5'

[colors.footer_bar]
foreground = '#44474c'
background = '#e4e2e3'

[colors.hints.start]
foreground = '#44474c'
background = '#c3c7cf'

[colors.hints.end]
foreground = '#44474c'
background = '#c3c7cf'

[colors.selection]
text = '#131314'
background = '#c6d3e5'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#c6d3e5'
yellow = '#535f6f'
blue = '#c6d3e5'
magenta = '#eaccae'
cyan = '#c3c7cf'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
