[colors.primary]
background = '#17130b'
foreground = '#ebe1d4'
 
[colors.cursor]
text = '#ebe1d4'
cursor = '#d1c5b4' 
 
[colors.vi_mode_cursor]
text = '#17130b'
cursor = '#eac16c' 
 
[colors.search.matches]
foreground = '#4d4639' 
background = '#b1cfa9' 
 
[colors.search.focused_match]
foreground = '#4d4639' 
background = '#eac16c' 
 
[colors.footer_bar]
foreground = '#4d4639' 
background = '#ebe1d4' 
 
[colors.hints.start]
foreground = '#4d4639' 
background = '#d8c4a0' 
 
[colors.hints.end]
foreground = '#4d4639' 
background = '#d8c4a0' 
 
[colors.selection]
text = '#17130b'
background = '#eac16c'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#eac16c' 
yellow = '#78590c' 
blue = '#eac16c' 
magenta = '#b1cfa9' 
cyan = '#d8c4a0' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
