[colors.primary]
background = '#121414'
foreground = '#e3e2e2'

[colors.cursor]
text = '#e3e2e2'
cursor = '#c7c6c6'

[colors.vi_mode_cursor]
text = '#121414'
cursor = '#b9c9ce'

[colors.search.matches]
foreground = '#464747'
background = '#b2cbd2'

[colors.search.focused_match]
foreground = '#464747'
background = '#b9c9ce'

[colors.footer_bar]
foreground = '#464747'
background = '#e3e2e2'

[colors.hints.start]
foreground = '#464747'
background = '#bfc8cb'

[colors.hints.end]
foreground = '#464747'
background = '#bfc8cb'

[colors.selection]
text = '#121414'
background = '#b9c9ce'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#b9c9ce'
yellow = '#516165'
blue = '#b9c9ce'
magenta = '#b2cbd2'
cyan = '#bfc8cb'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
