[colors.primary]
background = '#121316'
foreground = '#e3e2e5'
 
[colors.cursor]
text = '#e3e2e5'
cursor = '#c3c6cf' 
 
[colors.vi_mode_cursor]
text = '#121316'
cursor = '#a8c9f5' 
 
[colors.search.matches]
foreground = '#43474e' 
background = '#edbf7a' 
 
[colors.search.focused_match]
foreground = '#43474e' 
background = '#a8c9f5' 
 
[colors.footer_bar]
foreground = '#43474e' 
background = '#e3e2e5' 
 
[colors.hints.start]
foreground = '#43474e' 
background = '#bbc7da' 
 
[colors.hints.end]
foreground = '#43474e' 
background = '#bbc7da' 
 
[colors.selection]
text = '#121316'
background = '#a8c9f5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a8c9f5' 
yellow = '#3f6087' 
blue = '#a8c9f5' 
magenta = '#edbf7a' 
cyan = '#bbc7da' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
