[colors.primary]
background = '#121414'
foreground = '#e3e2e2'

[colors.cursor]
text = '#e3e2e2'
cursor = '#c1c8c8'

[colors.vi_mode_cursor]
text = '#121414'
cursor = '#aecccd'

[colors.search.matches]
foreground = '#414848'
background = '#e9bdaa'

[colors.search.focused_match]
foreground = '#414848'
background = '#aecccd'

[colors.footer_bar]
foreground = '#414848'
background = '#e3e2e2'

[colors.hints.start]
foreground = '#414848'
background = '#bdc9c9'

[colors.hints.end]
foreground = '#414848'
background = '#bdc9c9'

[colors.selection]
text = '#121414'
background = '#aecccd'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#aecccd'
yellow = '#476364'
blue = '#aecccd'
magenta = '#e9bdaa'
cyan = '#bdc9c9'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
