[colors.primary]
background = '#17120f'
foreground = '#ece0db'

[colors.cursor]
text = '#ece0db'
cursor = '#d6c3b8'

[colors.vi_mode_cursor]
text = '#17120f'
cursor = '#fab88e'

[colors.search.matches]
foreground = '#51443c'
background = '#95d0dc'

[colors.search.focused_match]
foreground = '#51443c'
background = '#fab88e'

[colors.footer_bar]
foreground = '#51443c'
background = '#ece0db'

[colors.hints.start]
foreground = '#51443c'
background = '#e2c0ab'

[colors.hints.end]
foreground = '#51443c'
background = '#e2c0ab'

[colors.selection]
text = '#17120f'
background = '#fab88e'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#fab88e'
yellow = '#845330'
blue = '#fab88e'
magenta = '#95d0dc'
cyan = '#e2c0ab'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
