[colors.primary]
background = '#121318'
foreground = '#e2e2e8'
 
[colors.cursor]
text = '#e2e2e8'
cursor = '#c3c6d2' 
 
[colors.vi_mode_cursor]
text = '#121318'
cursor = '#acc7ff' 
 
[colors.search.matches]
foreground = '#434750' 
background = '#efc052' 
 
[colors.search.focused_match]
foreground = '#434750' 
background = '#acc7ff' 
 
[colors.footer_bar]
foreground = '#434750' 
background = '#e2e2e8' 
 
[colors.hints.start]
foreground = '#434750' 
background = '#b9c7e7' 
 
[colors.hints.end]
foreground = '#434750' 
background = '#b9c7e7' 
 
[colors.selection]
text = '#121318'
background = '#acc7ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#acc7ff' 
yellow = '#345ea2' 
blue = '#acc7ff' 
magenta = '#efc052' 
cyan = '#b9c7e7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
