[colors.primary]
background = '#121410'
foreground = '#e3e3dd'

[colors.cursor]
text = '#e3e3dd'
cursor = '#c3c8bc'

[colors.vi_mode_cursor]
text = '#121410'
cursor = '#add19c'

[colors.search.matches]
foreground = '#43483f'
background = '#f6b4d2'

[colors.search.focused_match]
foreground = '#43483f'
background = '#add19c'

[colors.footer_bar]
foreground = '#43483f'
background = '#e3e3dd'

[colors.hints.start]
foreground = '#43483f'
background = '#bccbb2'

[colors.hints.end]
foreground = '#43483f'
background = '#bccbb2'

[colors.selection]
text = '#121410'
background = '#add19c'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#add19c'
yellow = '#47663b'
blue = '#add19c'
magenta = '#f6b4d2'
cyan = '#bccbb2'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
