[colors.primary]
background = '#121410'
foreground = '#e3e3dc'
 
[colors.cursor]
text = '#e3e3dc'
cursor = '#c4c8bb' 
 
[colors.vi_mode_cursor]
text = '#121410'
cursor = '#b1d095' 
 
[colors.search.matches]
foreground = '#44483e' 
background = '#f3b4d9' 
 
[colors.search.focused_match]
foreground = '#44483e' 
background = '#b1d095' 
 
[colors.footer_bar]
foreground = '#44483e' 
background = '#e3e3dc' 
 
[colors.hints.start]
foreground = '#44483e' 
background = '#becbaf' 
 
[colors.hints.end]
foreground = '#44483e' 
background = '#becbaf' 
 
[colors.selection]
text = '#121410'
background = '#b1d095'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b1d095' 
yellow = '#4b6635' 
blue = '#b1d095' 
magenta = '#f3b4d9' 
cyan = '#becbaf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
