[colors.primary]
background = '#131313'
foreground = '#e4e2e1'
 
[colors.cursor]
text = '#e4e2e1'
cursor = '#c3c8c4' 
 
[colors.vi_mode_cursor]
text = '#131313'
cursor = '#bccac4' 
 
[colors.search.matches]
foreground = '#434846' 
background = '#dac1bc' 
 
[colors.search.focused_match]
foreground = '#434846' 
background = '#bccac4' 
 
[colors.footer_bar]
foreground = '#434846' 
background = '#e4e2e1' 
 
[colors.hints.start]
foreground = '#434846' 
background = '#c3c7c4' 
 
[colors.hints.end]
foreground = '#434846' 
background = '#c3c7c4' 
 
[colors.selection]
text = '#131313'
background = '#bccac4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bccac4' 
yellow = '#54615c' 
blue = '#bccac4' 
magenta = '#dac1bc' 
cyan = '#c3c7c4' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
