[colors.primary]
background = '#131318'
foreground = '#e4e1e9'
 
[colors.cursor]
text = '#e4e1e9'
cursor = '#c8c5d0' 
 
[colors.vi_mode_cursor]
text = '#131318'
cursor = '#c1c1ff' 
 
[colors.search.matches]
foreground = '#47464f' 
background = '#e9b9d2' 
 
[colors.search.focused_match]
foreground = '#47464f' 
background = '#c1c1ff' 
 
[colors.footer_bar]
foreground = '#47464f' 
background = '#e4e1e9' 
 
[colors.hints.start]
foreground = '#47464f' 
background = '#c6c4dd' 
 
[colors.hints.end]
foreground = '#47464f' 
background = '#c6c4dd' 
 
[colors.selection]
text = '#131318'
background = '#c1c1ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#c1c1ff' 
yellow = '#585992' 
blue = '#c1c1ff' 
magenta = '#e9b9d2' 
cyan = '#c6c4dd' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
