[colors.primary]
background = '#1c110a'
foreground = '#f5ded2'

[colors.cursor]
text = '#f5ded2'
cursor = '#dfc0b0'

[colors.vi_mode_cursor]
text = '#1c110a'
cursor = '#ffb68b'

[colors.search.matches]
foreground = '#584236'
background = '#98cbff'

[colors.search.focused_match]
foreground = '#584236'
background = '#ffb68b'

[colors.footer_bar]
foreground = '#584236'
background = '#f5ded2'

[colors.hints.start]
foreground = '#584236'
background = '#ffb68b'

[colors.hints.end]
foreground = '#584236'
background = '#ffb68b'

[colors.selection]
text = '#1c110a'
background = '#ffb68b'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#ffb68b'
yellow = '#994700'
blue = '#ffb68b'
magenta = '#98cbff'
cyan = '#ffb68b'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
