[colors.primary]
background = '#131313'
foreground = '#e4e2e1'
 
[colors.cursor]
text = '#e4e2e1'
cursor = '#c2c8c7' 
 
[colors.vi_mode_cursor]
text = '#131313'
cursor = '#b8caca' 
 
[colors.search.matches]
foreground = '#424848' 
background = '#dec0b3' 
 
[colors.search.focused_match]
foreground = '#424848' 
background = '#b8caca' 
 
[colors.footer_bar]
foreground = '#424848' 
background = '#e4e2e1' 
 
[colors.hints.start]
foreground = '#424848' 
background = '#c1c8c7' 
 
[colors.hints.end]
foreground = '#424848' 
background = '#c1c8c7' 
 
[colors.selection]
text = '#131313'
background = '#b8caca'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b8caca' 
yellow = '#506262' 
blue = '#b8caca' 
magenta = '#dec0b3' 
cyan = '#c1c8c7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
