[colors.primary]
background = '#272e33'
foreground = '#d3c6aa'

[colors.cursor]
text = '#2e383c'
cursor = '#d3c6aa'

[colors.vi_mode_cursor]
text = '#272e33'
cursor = '#a7c080'

[colors.search.matches]
foreground = '#9da9a0'
background = '#464e53'

[colors.search.focused_match]
foreground = '#9da9a0'
background = '#464e53'

[colors.footer_bar]
foreground = '#9da9a0'
background = '#272e33'

[colors.hints.start]
foreground = '#9da9a0'
background = '#7fbbb3'

[colors.hints.end]
foreground = '#9da9a0'
background = '#7fbbb3'

[colors.selection]
text = '#9da9a0'
background = '#464e53'


[colors.normal]
black = '#343f44'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#859289'


[colors.bright]
black = '#868d80'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#9da9a0'


[colors.dim]
black = '#343f44'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#859289'