theme = "monokai_pro_octagon"

[editor]
evil = true
line-number = "absolute"
bufferline = "multiple"
mouse = true
color-modes = true
completion-replace = false 
lsp.enable = true
lsp.display-messages = true
lsp.display-inlay-hints = true
cursorline = true
true-color = true
scrolloff = 100


[keys.insert]
j = { k = "normal_mode"}

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"
