theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
color-modes = true
completion-replace = false 
lsp.enable = true
lsp.display-messages = true
lsp.display-inlay-hints = true
cursorline = true
true-color = true
scrolloff = 10


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
S-x = "extend_line_above"
"tab" = { s = "switch_case", u = "switch_to_uppercase",  l = "switch_to_lowercase" }
_ = "goto_first_nonwhitespace"

[keys.select]
"tab" = { s = "switch_case", u = "switch_to_uppercase",  l = "switch_to_lowercase" }

[keys.insert]
j = { k = "normal_mode"}

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
